name: bump

on:
  push:
    branches: ["**"]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: version and bump
        run: |
          echo "Made a change in build ${{github.run_number}}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --tags

          LAST_TAG=0.0.0
          if [ ! -z $(git tag --sort=v:refname | tail -1) ]; then
            LAST_TAG=$(git tag --sort=v:refname | tail -1)
          fi

          echo $LAST_TAG

          MAJOR=$(echo $LAST_TAG | awk -F "." '{print $1}' | sed 's/v//')
          MINOR=$(echo $LAST_TAG | awk -F "." '{print $2}')
          PATCH=$(echo $LAST_TAG | awk -F "." '{print $3}')

          if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
            NEW_TAG="v$MAJOR.$((MINOR + 1)).0"
          else
            NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          fi

          echo $NEW_TAG

          git tag -am "Tagging for release ${NEW_TAG}" ${NEW_TAG}
          git push origin ${NEW_TAG}
